### ISSUE TITLE
Where is DecisionMaker definition?

### ISSUE THREAD

**Issue by telecran-telecrit** [bourbonut/dqn-pacman#3]
What is DecisionMaker class, which is used in fast.py record?

**Comment by bourbonut** [comment]
`fast.py` is an old file for testing purposes, that I should delete. The class `DecisionMaker` was deleted from previous version of the code.
Here is the last version of the class:
```python
import random, math, torch
from .parameters import EPS_MAX, EPS_MIN, EPS_DECAY, N_ACTIONS, device
from utils.utils import ACTIONS, REVERSED


class DecisionMaker:
    def __init__(self, steps_done, policy_DQN):
        self.steps_done = steps_done
        self.old_action = 3

    def select_action(self, state, policy_DQN, display, learn_counter):
        sample = random.random()
        eps_threshold = max(EPS_MIN, EPS_MAX - (EPS_MAX - EPS_MIN) * learn_counter / EPS_DECAY)
        self.steps_done += 1
        with torch.no_grad():
            q_values = policy_DQN(state)
        display.data.q_values.append(q_values.max(1)[0].item()) # old way to collect data for visualization
        if sample > eps_threshold:
            # Optimal action
            return q_values.max(1)[1].view(1, 1)
        else:
            # Random action
            action = random.randrange(N_ACTIONS)
            while action == REVERSED[self.old_action]:
                action = random.randrange(N_ACTIONS)
            return torch.tensor([[action]], device=device, dtype=torch.long)
```

In the current version of the code, it was replaced by the method [`DataHandler.select_action`](https://github.com/bourbonut/dqn-pacman/blob/main/main.py#L58-L76). If you want to use the function `record` now, you should use [`evaluation`](https://github.com/bourbonut/dqn-pacman/blob/main/evaluation/utils.py#L103) module by following [this](https://github.com/bourbonut/dqn-pacman/tree/main?tab=readme-ov-file#evaluation).
This change comes from the update of the frontend. In previous version, I used [`streamlit`](https://streamlit.io/) to make a quick frontend. You can check out [`display.py`](https://github.com/bourbonut/dqn-pacman/blob/fb98fd01c9c5d48681460c00c72276b90a33426e/utils/display.py) to see how it worked.
However, I wanted a more flexible frontend experience, quicker if possible and more customizable. I mixed [`Quart`](https://quart.palletsprojects.com/en/latest/), a web framework (which is the same as Flask but asynchronous and offers websockets)  with [`d3js`](https://d3js.org/), a Javascript library for data visualization. Now, `Display` has become [`Buffer`](https://github.com/bourbonut/dqn-pacman/blob/main/deep_Q_network/buffer.py).



Note: You can check out [`detroit`](https://github.com/bourbonut/detroit) if you are interested to make visualizations in Python with `d3js`
